# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    working_directory: ~

    docker:
    	- image: circleci/node:7.10

    steps:
      # Checkout the code from the branch into the docker
      - checkout

      # Log the current branch and working directory
      - run:
          name: Show current branch and working directory
          command: pwd && echo ${CIRCLE_BRANCH}

      # Download and cache dependencies for frontend
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./frontend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install project dependencies for frontend
      - run:
          name: Install local dependencies
          command: cd ~/frontend && npm install

      # Cache local dependencies for frontend
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./frontend/package.json" }}

      - run:
          name: Unit & Integration tests for Frontend
          command: npm run test

      # Run e2e tests
      - run:
          name: E2E tests for Frontend
          command: npm run e2e


  build-and-deploy:
   working_directory: ~
    docker:
      - image: circleci/node:7.10

    steps:
      # Checkout the code from the branch into the working_directory
      - checkout

      # Log the current branch and working directory
      - run:
          name: Show current branch and working directory
          command: pwd && echo ${CIRCLE_BRANCH}

      # Download and cache dependencies for frontend
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./frontend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install project dependencies for frontend
      - run:
          name: Install local dependencies
          command: cd ~/frontend && npm install

      # Cache local dependencies for frontend
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./frontend/package.json" }}

      # Build frontend
      - run:
          name: Build Frontend
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build:prod && mv ./frontend/www/ ./backend/www/
            else
              npm run build
            fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - build-and-deploy
		requires:
      - test


