# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout-code:
    working_directory: ~
    docker:
      - image: circleci/node:7.10
      
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: pwd && ls && echo ${CIRCLE_BRANCH}
      
  prepare-frontend:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:7.10

    steps:
      # Log the current branch
      - run:
          name: Show current branch
          command: pwd && ls && echo ${CIRCLE_BRANCH}

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install

      # Cache local dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


  test-frontend:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:7.10

    steps:
      # Log
      - run:
          name: Log
          command : pwd && ls
      # Run unit tests
      - run:
          name: Unit & Integration tests
          command: npm run test

      # Run e2e tests
      - run:
          name: E2E tests
          command: npm run e2e

  build-frontend:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:7.10

    steps:
      # Build project
      - run:
          name: Build project
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build:prod && mv www/ ../backend/www/
            else
              npm run build
            fi

  prepare-backend:
    working_directory: ~/backend
    docker:
      - image: circleci/node:7.10
    steps:
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install

      # Cache local  dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout-code
      - prepare-frontend:
          requires:
            - checkout-code
            
      - prepare-backend:
          requires:
            - checkout-code

      - test-frontend:
          requires:
            - prepare-frontend
      #- test-backend
      #  requires:
      #    - prepare-backend

      - build-frontend:
          requires:
            - test-frontend

      #- deploy-frontend
      #  requires:
      #      - build-frontend
      #  filters:
      #    branches:
      #      only:
      #        - master
